/**
 * Standard error codes used across all services
 */
const ErrorCodes = {
    // Validation errors (400)
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    INVALID_CURRENCY: 'INVALID_CURRENCY',

    // Authentication/Authorization errors (401, 403)
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',

    // Resource errors (404)
    PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // Business logic errors (409, 422)
    DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
    PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
    INVALID_PAYMENT_STATUS: 'INVALID_PAYMENT_STATUS',

    // External service errors (502, 503)
    PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',

    // System errors (500)
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    CACHE_ERROR: 'CACHE_ERROR',
    LOCK_ACQUISITION_FAILED: 'LOCK_ACQUISITION_FAILED',

    // Rate limiting (429)
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

module.exports = { ErrorCodes };
